gestor/api/urls.py
from django.conf.urls.defaults import *

# Final URL extension
# Examples: /show /show.m /show.xml /show.json
ext = r'(\.(?P<extension>\w{1,4}))?$'

urlpatterns = patterns('',
    
    # Action Items
    (r'^action_items'                        + ext,  'gestor.api.views.action_items',),
    (r'^action_items/todo'                       + ext,  'gestor.api.views.action_items_todo',),
    (r'^action_items/(?P<item_id>\d+)'      + ext,  'gestor.api.views.action_item',),
    
    # Projects
    (r'^projects'                        + ext,  'gestor.api.views.projects',),
    (r'^projects/(?P<project_id>\d+)'   + ext,  'gestor.api.views.projects_show',),
)

gestor/urls.py
from django.conf.urls.defaults import *
from gestor.models import Project, Note, ActionItem
from activitystream.models import Activity

from gestor.forms import NoteForm, ActionForm

from gestor.feeds import ActionItemFeed
from activitystream.feeds import ActivityStreamFeed

feeds = {
    'ActionItems': ActionItemFeed,
    'stream': ActivityStreamFeed,
}


urlpatterns = patterns('',
	(r'^$', 'django.views.generic.simple.direct_to_template', {'template':'splashpage.html'}),
	(r'^main/$', 'gestor.views.main_page'),
	
	(r'^dashboard/$', 'gestor.views.project_dashboard'),
	
	(r'^project/(?P<object_id>\d+)/$', 'gestor.views.project_detail', ),
	(r'^project/(?P<object_id>\d+)/close/$', 'gestor.views.project_close', ),
	(r'^project/(?P<object_id>\d+)/re-open/$', 'gestor.views.project_reopen', ),
	(r'^project/(?P<object_id>\d+)/fast_edit/$', 'gestor.views.project_fastedit', ),
	(r'^project/(?P<object_id>\d+)/edit/$', 'gestor.views.project_edit', ),
	
	# Note: the following is dangerous if you ever change the project's pk to strings
	(r'^project/create/$', 'gestor.views.project_create', ),
	
    (r'^feeds/(?P<url>.*)/$', 'gestor.views.protected_feed', {'feed_dict': feeds}),
    (r'^ical/ActionItems/(?P<username>([A-z]|[0-9]|[_])+)/$', 'gestor.views.action_ical',),
	
	(r'^action/(?P<object_id>\d+)/$', 'gestor.views.action_detail', ),
	(r'^action/in/(?P<object_id>\d+)/$', 'gestor.views.action_create', ),
	(r'^action/(?P<object_id>\d+)/edit/$', 'gestor.views.action_edit',),
	(r'^action/(?P<object_id>\d+)/delete/$', 'gestor.views.action_delete',),
	(r'^action/(?P<object_id>\d+)/finish/$', 'gestor.views.action_finish', ),

	
	(r'^note/(?P<object_id>\d+)/$', 'gestor.views.note_detail', ),
	(r'^note/in/(?P<object_id>\d+)/$', 'gestor.views.note_create', ),
	(r'^note/(?P<object_id>\d+)/edit/$', 'gestor.views.note_edit',),
	(r'^note/(?P<object_id>\d+)/delete/$', 'gestor.views.note_delete',),
	
	(r'^actionnote/(?P<object_id>\d+)/$', 'gestor.views.actionnote_detail', ),
	(r'^actionnote/in/(?P<object_id>\d+)/$', 'gestor.views.actionnote_create', ),
	(r'^actionnote/(?P<object_id>\d+)/edit/$', 'gestor.views.actionnote_edit',),
	(r'^actionnote/(?P<object_id>\d+)/delete/$', 'gestor.views.actionnote_delete',),
	(r'^search/$', 'gestor.views.search_everything',),

    (r'^stream/(?P<all>all/?)?$', 'activitystream.views.activity_stream',),
    (r'^stream/(?P<stream_id>\d+)/', 'activitystream.views.activity_stream_detail'),

)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings


from mainsite.models import News
from mainsite.feeds import NewsFeed

feeds = {
	'noticias': NewsFeed,
}

info_dict = {
	'queryset': News.objects.filter(is_published=True),
	'date_field': 'date',
	'allow_empty': 1,
}


admin.autodiscover()

urlpatterns = patterns('',
	(r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	(r'^dynamic-media/jsi18n/$', 'django.views.i18n.javascript_catalog'), 

	#(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	(r'^admin/(.*)', admin.site.root),

	(r'^gestor/api/', include('gestor.api.urls')),
	(r'^gestor/', include('gestor.urls')),
	(r'^accounts/', include('accounts.urls')),
	(r'^formacao/', include('formacao.urls')),
	
	(r'^users/(?P<username>([A-z]|[0-9]|[_])+)/$', 'accounts.views.profile'),
	(r'^users/(?P<username>([A-z]|[0-9]|[_])+)/curriculum/$', 'cvmanager.views.curriculum'),

	(r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
	
	# News Archives
	(r'^noticias/arquivo/$', 'mainsite.views.archive'),
	(r'^noticias/arquivo/(?P<year>\d{4})/$', 'django.views.generic.date_based.archive_year', dict( info_dict, template_name='news_archive_year.html' )),
	(r'^noticias/arquivo/(?P<year>\d{4})/(?P<month>\w{1,2})/$', 'django.views.generic.date_based.archive_month', dict( info_dict, 
																													   month_format='%m',
																													   template_name='news_archive_month.html',
																													   extra_context={'truncate':'true'})),
	(r'^noticias/arquivo/(?P<year>\d{4})/(?P<month>\w{1,2})/(?P<day>\w{1,2})/$', 'django.views.generic.date_based.archive_day', dict( info_dict,
																																	  month_format='%m',
																																	  template_name='news_archive_day.html',
																																	  extra_context={'truncate':'true'})),
	
	(r'^noticias/(?P<object_id>\d+)/$', 'mainsite.views.news_detail', {'template_name': 'news_detail.html'}),
	
	(r'^noticias/create/$', 'mainsite.views.create_news'),

	(r'^noticias/pesquisar/$', 'mainsite.views.search_news'),
	
	# New site (hard-coded, no more flat pages)
	(r'^$', 'mainsite.views.news_index', dict( info_dict, template_name='index.html' )),
	(r'^carreiras/$', 'django.views.generic.simple.direct_to_template', {'template': 'carreiras.html'}),
	(r'^contactos/$', 'django.views.generic.simple.direct_to_template', {'template': 'contactos.html'}),
	(r'^parceiros/$', 'django.views.generic.simple.direct_to_template', {'template': 'parceiros.html'}),
	(r'^servicos/$', 'django.views.generic.simple.direct_to_template', {'template': 'servicos.html'}),
	(r'^sobre/$', 'django.views.generic.simple.direct_to_template', {'template': 'sobre.html'}),
	
	# RH's Survey
	(r'^rh/$', 'django.views.generic.simple.direct_to_template', {'template': 'inquerito.html'}),
	
	# Public curriculums - must be the last one.
	(r'^(?P<username>([A-z]|[0-9]|[_])+)/$', 'cvmanager.views.public_curriculum'),
)

gestor/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

from activitystream.models import Activity

class ProjectManager(models.Manager):
	def get_query_set(self):
		return super(ProjectManager,self).get_query_set().filter(active=True)


class Project(models.Model):
	name = models.CharField(max_length=100, default=None)
	description = models.TextField(blank=True)
	active = models.BooleanField(default=True)
	manager = models.ForeignKey(User, related_name='projects_managed')
	team = models.ManyToManyField(User, related_name = 'projects_working')
	start_date = models.DateField()
	end_date = models.DateField()
	
	objects = models.Manager()
	workspace = ProjectManager()
	
	class Meta:
		ordering = ["-start_date"]
		permissions = [ ('view_project','Can view Projects'), 
						('view_intern_projects', 'Can view intern Projects'),
						('view_late_projects', 'Can view late Projects'),
						('view_late_users', 'Can view late Users') ]
	
	def __unicode__(self):
		return u"%s" % self.name
		
	def get_absolute_url(self):
		return "/gestor/project/%d/" % self.id
		
	def has_user(self,user):
		if user in self.team.all() or user == self.manager:
			return True
		return False
		
	def check_user(self,user):
		if not ( user.has_perm('gestor.view_project') or self.has_user(user) or (user.has_perm('gestor.view_intern_projects') and self.isIntern()) ):
			return False
		else: return True
	
	def check_manager(self, user, perm):
		if user != self.manager and not user.has_perm('gestor.' + perm + '_project'):
			return False
		else: return True
	
	def isIntern(self):
		return self.name.split('-')[0].lower() == 'jk'
	
	def ratio(self):
		done = self.actionitem_set.filter(done=True).count()
		total = self.actionitem_set.all().count()
		if total:
			return float(done) / total
		else:
			return 0
			
	def percentage(self):
		return str(int(round(self.ratio() * 100))) + "%"
	
	def createActivity(self, action):
		activity = Activity( message_type = Activity.MSG_GESTOR_PROJECT, 
							 action_type = action, 
							 object_id = self.id,
							 message = self.name )
		activity.save()
	
	def save(self):
		new_object = not self.id
		
		super(Project, self).save() # Call the "real" save() method
		
		if new_object:
			action = Activity.ACTION_CREATE
		else:
			action = self.active and Activity.ACTION_EDIT or Activity.ACTION_CLOSE
		self.createActivity(action)
						     
	    
	def delete(self):
		super(Project, self).delete() # Call the "real" delete() method
		self.createActivity(Activity.ACTION_DELETE)

class ActionItem(models.Model):
	project = models.ForeignKey(Project)
	title = models.CharField(max_length=100, default=None)
	description = models.TextField(blank=True, null=True)
	author = models.ForeignKey(User, related_name='actionitem_set')
	targets = models.ManyToManyField(User, related_name = 'actionitem_todo')
	set_date = models.DateField(auto_now=True)
	due_date = models.DateField(blank=True, null=True)
	done = models.BooleanField(default=False)
	priority = models.IntegerField(default=2, choices=((1, 'High') ,(2, 'Medium'), (3, 'Low')) )

	class Meta:
		ordering = ('done', 'priority', 'due_date')
	
	def __unicode__(self):
		return u"%s" % self.title
	
	def get_absolute_url(self):
		return "/gestor/action/%s/" % self.id 
	
	def createActivity(self, action):
		activity = Activity( message_type = Activity.MSG_GESTOR_ACTION_ITEM, 
							 action_type = action, 
							 object_id = self.id,
							 message = self.title )
		activity.save()
	
	def save(self):
		new_object = not self.id
		
		super(ActionItem, self).save() # Call the "real" save() method
		
		if new_object:
			action = Activity.ACTION_CREATE
		else:
			action = not self.done and Activity.ACTION_EDIT or Activity.ACTION_CLOSE
		self.createActivity(action)
						     
	    
	def delete(self):
		super(ActionItem, self).delete() # Call the "real" delete() method
		self.createActivity(Activity.ACTION_DELETE)	
	

class Note(models.Model):
	project = models.ForeignKey(Project)
	title = models.CharField(max_length=100, default=None)
	description = models.TextField(blank=True, null=True)
	author = models.ForeignKey(User)
	set_date = models.DateField(auto_now=True)
	
	class Meta:
		ordering = ["-set_date"]

	def __unicode__(self):
		return u"%s" % self.title
	
	def get_absolute_url(self):
		return "/gestor/note/%s/" % self.id
	
	def createActivity(self, action):
		activity = Activity( message_type = Activity.MSG_GESTOR_NOTE, 
							 action_type = action, 
							 object_id = self.id,
							 message = self.project.name )
		activity.save()
		
	def save(self):
		new_object = not self.id
		
		super(Note, self).save() # Call the "real" save() method
		
		if new_object:
			action = Activity.ACTION_CREATE
		else:
			action = Activity.ACTION_EDIT
		self.createActivity(action)
						     
	def delete(self):
		super(Note, self).delete() # Call the "real" delete() method
		self.createActivity(Activity.ACTION_DELETE)		
			
class ActionNote(models.Model):
	actionitem = models.ForeignKey(ActionItem)
	description = models.TextField(blank=True, null=True)
	author = models.ForeignKey(User)
	set_date = models.DateField(auto_now=True)
	
	class Meta:
		ordering = ["-set_date"]

	def __unicode__(self):
		return u"%s" % self.actionitem

	def get_absolute_url(self):
		return "/gestor/actionnote/%s/" % self.id

	def createActivity(self, action):
		activity = Activity( message_type = Activity.MSG_GESTOR_ACTION_NOTE, 
							 action_type = action, 
							 object_id = self.id,
							 message = self.actionitem.title )
		activity.save()
		
	def save(self):
		new_object = not self.id
		
		super(ActionNote, self).save() # Call the "real" save() method
		
		if new_object:
			action = Activity.ACTION_CREATE
		else:
			action = Activity.ACTION_EDIT
		self.createActivity(action)
						     
	def delete(self):
		super(ActionNote, self).delete() # Call the "real" delete() method
		self.createActivity(Activity.ACTION_DELETE)		
		

mainsite/models.py
from django.db import models
from django.contrib.auth.models import User

import datetime

class News(models.Model):
	""" Website News """
	
	title = models.CharField(max_length=200, default=None)
	date = models.DateTimeField()
	is_published = models.BooleanField(default=True, help_text=" Only published posts will be visible to the outside users. However, it will be visible to administrators like yourself!")
	
	body = models.TextField(default=None)
	author = models.ForeignKey(User, related_name='news_set', null=True, blank=True, default='')
	
	def save(self):
		if not self.id:
			self.date = datetime.datetime.now()
		super(News, self).save()
	
	def __unicode__(self):
		return u"%s" % self.title
		
	def get_absolute_url(self):
		return u"/noticias/%s/" % self.id
	
	def get_admin_change_url(self):
		return u"/admin/mainsite/news/%s/" % self.id
		
	def has_author(self):
		try: self.author.id
		except: return False
		
		return True
		
	class Meta:
		verbose_name_plural = "news"
		ordering = ["-date"]

gestor/forms.py
from django.forms import *
from gestor.models import Note, ActionItem, Project, ActionNote
from django.contrib.auth.models import User
from django.contrib.admin.widgets import AdminDateWidget, AdminFileWidget

import datetime


class CommonForm(ModelForm):
	author = ModelChoiceField(queryset=User.objects.all(),widget=HiddenInput())
	project = ModelChoiceField(queryset=Project.objects.all(),widget=HiddenInput())
	notification = BooleanField(help_text=" (Sends email to project members)",required=False)

class NoteForm(CommonForm):
	description = CharField(widget=Textarea(),help_text="(supports <a href='http://hobix.github.com/hobix/textile/' target='_blank'>textile</a>)")	
	class Meta:
		model = Note

class ActionNoteForm(ModelForm):
	author = ModelChoiceField(queryset=User.objects.all(),widget=HiddenInput())
	actionitem = ModelChoiceField(queryset=ActionItem.objects.all(),widget=HiddenInput())
	notification = BooleanField(help_text=" (Sends email to action item team)",required=False)
	
	description = CharField(widget=Textarea(),help_text="(supports <a href='http://hobix.github.com/hobix/textile/' target='_blank'>textile</a>)")	
	class Meta:
		model = ActionNote
				
class ActionForm(CommonForm):
	due_date = DateTimeField(widget=AdminDateWidget())
	description = CharField(widget=Textarea(),help_text="(supports <a href='http://hobix.github.com/hobix/textile/' target='_blank'>textile</a>)")
	class Meta:
		model = ActionItem
	
class ProjectForm(ModelForm):
	description = CharField(widget=Textarea(),help_text="(supports <a href='http://hobix.github.com/hobix/textile/' target='_blank'>textile</a>)")
	
	start_date = DateTimeField(widget=AdminDateWidget())
	end_date = DateTimeField(widget=AdminDateWidget())
	
	team = ModelMultipleChoiceField(queryset=User.objects.all().order_by('username'))
	
	class Meta:
		model = Project
		
class SearchForm(Form):
	find = CharField(label="Looking for:")

gestor/templates/action_feed_description.html
{% load markup %}
{{ obj.description|force_escape|textile }}

gestor/templates/action_feed_title.html
{% load humanize %}
{{ obj.title }} (Dues: {{object.due_date|naturalday|default_if_none:"Never"}})

gestor/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
   "http://www.w3.org/TR/html4/loose.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" type="text/css" href="/media/admin/css/forms.css" />
	<link rel="stylesheet" type="text/css" href="/media/admin/css/widgets.css" />
	<link rel="stylesheet" type="text/css" href="/media/admin/css/base.css" />

	<script type="text/javascript" src="/dynamic-media/jsi18n/"></script>
	<script type="text/javascript" src="/media/admin/js/core.js"></script>
	<script type="text/javascript" src="/media/admin/js/dateparsing.js"></script>
	<script type="text/javascript" src="/media/admin/js/admin/RelatedObjectLookups.js"></script>
	<script type="text/javascript" src="/media/admin/js/calendar.js"></script>
	<script type="text/javascript" src="/media/admin/js/admin/DateTimeShortcuts.js"></script>
	
	{% block feeds %}
		<link rel="alternate" type="application/rss+xml" title="User Feeds" href="/gestor/feeds/ActionItems/{{user.username}}" />
	{%endblock feeds%}

	<script src="{{MEDIA_URL}}js/prototype.js"></script>
	<script src="{{MEDIA_URL}}js/tooltip.js"></script>
	<script src="{{MEDIA_URL}}js/gestor.js"></script>
	<link rel="stylesheet" href="{{MEDIA_URL}}css/common.css" type="text/css" media="screen" title="no title" charset="utf-8">
	<link rel="stylesheet" href="{{MEDIA_URL}}css/master.css" type="text/css" media="screen" title="no title" charset="utf-8">
	
	<link rel="shortcut icon" href="{{MEDIA_URL}}images/favicon.ico">
	<link rel="icon" type="image/png" href="{{MEDIA_URL}}images/favicon.png">

	<title>{% block title %}{% endblock title %} - Gestor jeKnowledge</title>
</head>
<body>
	<div id="container">
		
		<div id="header">
			
			<a href="/gestor/" style="float: left;"><img src="{{MEDIA_URL}}images/logo.gif" alt="jeKnowledge"></a>
			
			{% if request.user.is_authenticated %}
			<div style="float: right; padding-right: 50px; padding-top: 40px;">
			<form action="/gestor/search/" method="post"><input type="text" name="find" value="Search..." id="id_find" onclick="this.clear();"/> <input type="submit" value="Find" /></form>
			</div>
			{% endif %}
			
		</div>
		
		{% include "sidebar_gestor.html" %}
		
		<div id="main">
			<div id="messages">
				{% if messages %}
				<ul>
				    {% for message in messages %}
				    <li>{{ message }}</li>
				    {% endfor %}
				</ul>
				{% endif %}
			</div>
			<div id="content">
				{% block content %}
				{% endblock %}
			</div>
			
		</div>
		
		
	</div>
</body>
</html>

gestor/templates/file_detail.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}{{ object.title }} - {{object.project.name}}{% endblock title %}

{% block content %}
	<div class="file_detail">
		<h1>{{ object.title }}</h1>
		
		<div class="status">
			Added {{object.set_date|naturalday}}
		</div>
	
		<p><b class="label">Project:</b> <a href="{{object.project.get_absolute_url}}">{{object.project.name}}</a></p>
		<p><b class="label">Author:</b> <a href="{{object.author.get_absolute_url}}">{{object.author.get_full_name}}</a></p>
		<p><b class="label">Download:</b> <a href="{{object.content.url}}">{{object.title}}</a></p>

		<div class="actions">
			<ul class="raw">
			<li><a href="{{object.content.url}}" alt='Download File' title='Download File'><img src="{{MEDIA_URL}}icons/page_save.png" /> Download File</a>
			<li><a href="{{object.get_absolute_url}}edit/"><img src="{{MEDIA_URL}}icons/page_edit.png" alt="Edit File"> Edit File</a></li>
			<li><a href="{{object.get_absolute_url}}delete/"  onclick="return confirm('Are you sure you want to delete?')"><img src="{{MEDIA_URL}}icons/page_delete.png" alt="Delete File"> Delete File</a></li>
			</ul>
		</div>

	</div>
{% endblock %}

gestor/templates/file_edit.html
{% extends "base.html" %}

{% block title %} Edit File {% endblock title %}


{% block content %}
	<h1>Edit File</h1>
	<div class="note_form">
		<fieldset>
			<form action="" method="post" enctype="multipart/form-data">
				{{ form.as_ul }}
				<div class="clear"><input type="submit" value="Save" /></div>
			</form>
		</fieldset>
	</div>
{% endblock %}

gestor/templates/project_detail.html
{% extends "base.html" %}
{% load humanize %}
{% load datecolor %}
{% load markup %}
{% load proj_utils %}

{% block title %}{{ object.name }}{% endblock title %}


{% block content %}
	<div class="project_detail">
		<h1>{{ object.name }}</h1>
	
		<div class="status">
			{% if object.active %}
				<b>Active</b> since {{object.start_date|naturalday}}
			{% else %}
				<b>Finished</b> (from {{object.start_date|naturalday}} to {{object.end_date|naturalday}})
			{% endif %}
		</div>
		<div class="progress_box">
			<div class="progress_bar" style="width: {% widthratio object.ratio 1 400 %}px;">
				{{ object.percentage }}
			</div>
		</div>
		
		{% if perms.gestor.change_project or request.user|ismanager:object %}
			<div class="description clear text">
				<div id="editable_description">{{object.description|force_escape|textile}}</div>
				<div id="editable_description_editor" style="display: none;">
					<textarea id="editable_description_edit" 
						name="editable_description" rows="4" cols="60">{{object.description}}</textarea>
					<br />
					<input id="editable_description_save" type="button" value="SAVE" />
					<input id="editable_description_cancel" type="button" value="CANCEL" />
				</div>
			</div>
		{% else %}
			<div class="description clear text">{{object.description|force_escape|textile}}</div>
		{% endif %}
		
		<div>
			<p><span class="label">Manager: </span> <span class="manager"><a href="{{object.manager.get_absolute_url}}">{{object.manager.get_full_name}}</a></span></p>
		</div>
		
		{% if perms.gestor.change_project or request.user|ismanager:object %}
		<div>
			<hr />
			<p><span class="label">Management Area:</span></p>
			
			<div class="manager_options smaller">
			
				<a href="/gestor/project/{{object.id}}/edit/"><img src="/media/icons/pencil.png" width="13px" alt=""> Edit this Project</a><br />
				{% if object.active %}
					<a href="/gestor/project/{{object.id}}/close"><img src="/media/icons/box.png" width="13px" alt="">  Close this Project</a>
				{% else %}
					<a href="/gestor/project/{{object.id}}/re-open"><img src="/media/icons/briefcase.png" width="13px" alt=""> Re-open this Project</a>
				{% endif %}
				
			</div>
			<hr />
		</div>
		{% endif %}
		
		<div class="three_col">
			<p><span class="label">Team: </span></p> <ul class="members">
				{% for user in object.team.all %}
					<li><a href="{{user.get_absolute_url}}">{{user.get_full_name}}</a></li>
				{% endfor %}
			</ul>
		</div>
		<div class="three_col">
			<p><span class="label">Action Items: </span></p> <ul class="action-items">
				{% for item, dist in actionitems %}
					<li class="{{item|colorstatus}}" title="Dues: {%if dist%}{{dist}} days{%else%}Never{%endif%}. Priority: {{item.get_priority_display}}">
						<a href="{{item.get_absolute_url}}">{{item.title}}</a>
					</li>
				{% endfor %}
			</ul>
			<img src="{{MEDIA_URL}}icons/cog_add.png" alt=""> <a href="/gestor/action/in/{{object.id}}">New ActionItem</a><br />
			<img src="{{MEDIA_URL}}icons/cog_go.png" alt=""> <a href="#" id="toggle-history">Toggle History</a>
			
		</div>
		<div class="three_col">
			<p><span class="label">Notes: </span></p> <ul class="notes">
				{% for note in notes %}
					<li><a href="{{note.get_absolute_url}}">{{note.title}}</a></li>
				{% endfor %}
			</ul>
			<img src="{{MEDIA_URL}}icons/note_add.png" alt=""> <a href="/gestor/note/in/{{object.id}}">New Note</a>
		</div>
		<div class="clear"></div>
		
		
	</div>
{% endblock %}

gestor/templates/sidebar_gestor.html
<div id="sidebar">

{% if not user.is_anonymous %}
	<div id="menu">
		{% block menu %}
			{% load todo %}
			{% load projecting %}
			{% load dashboard %}
			
			
			<h3>Todo List</h3>
			{{request.user.username|todo|safe}}

			<p class="icons">
				<a href="/gestor/feeds/ActionItems/{{request.user.username}}/"><img src="/media/icons/rss.png" alt="RSS"></a>
				<a href="/gestor/ical/ActionItems/{{request.user.username}}/"><img src="/media/icons/calendar.png" alt="iCal"></a>
			</p>
			
			
			<h3>Projects</h3>
			
			<ul id="project_list" class="projects">	

				{% for project in request.user|workspace %}
					{% ifequal project.manager request.user %}
						<li class="owner">
					{% else %}
						<li>
					{% endifequal %}
						<a href="{{project.get_absolute_url}}" title="{% if project.name|length|bigger_than:"25" %}{{project.name}}{%endif%}">{{project.name|trunc:"25"}}</a></li>
				{% endfor %}

				{% if perms.gestor.add_project %}
					<span class="smaller"><a href="/gestor/project/create/"><img src="/media/icons/add.png" alt="add" /> Create a Project</a></span>
				{% endif %}
			</ul>
			
			
			<h3>Links</h3>
			
			<ul>
				<li><a href="http://wiki.jeknowledge.pt/">Wiki <img src="{{MEDIA_URL}}icons/new.png" /></a></li>
			</ul>
			
			<h3>Account</h3>
			
			<ul>
				{% if request.user.is_staff  %}
					<li><a href="/admin">Administration</a></li>
				{% endif %}
				{% if perms.mainsite.add_news %}<li><a href="/noticias/create/">Create a News Post</a></li>{% endif %}
				
				{% if perms.gestor.view_intern_projects %}<li><a href="/gestor/dashboard/">Dashboard</a></li>{% endif %}
				{% if perms.activitystream.view_everything %}<li><a href="/gestor/stream">Activity Stream</a></li>{% endif %}
			</ul>
			<ul>	
				<li><a href="/accounts/profile">My Profile</a></li>
				<li><a href="/accounts/edit_profile">Edit your Profile <img src="{{MEDIA_URL}}icons/new.png" /></a></li>
				<li><a href="/accounts/edit_curriculum">Edit your Curriculum</a></li>
				<li><a href="/accounts/password_change">Change Password</a></li>
				<li><a href="/accounts/logout">Logout</a></li>
			</ul>
			
		{% endblock %}
	</div>
{% endif %}

</div>