accounts/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns('',
    (r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
	(r'^logout/$', 'django.contrib.auth.views.logout_then_login', {'login_url': '/gestor/'}),
	
	(r'^profile/$', 'accounts.views.redirect_to_profile'), 
	(r'^edit_profile/$', 'accounts.views.edit_my_profile'),
	
	(r'^edit_curriculum/$', 'cvmanager.views.edit_my_curriculum'),
	
	(r'^password_change/$', 'django.contrib.auth.views.password_change', {'template_name': 'password_change.html'}), 
	(r'^password_change/done/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'password_change_done.html'}), 
	
	(r'^password_reset/$', 'django.contrib.auth.views.password_reset', {'template_name': 'password_reset.html'}),
	(r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done', {'template_name': 'password_reset_done.html'}),
	(r'^password_reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)$', 'django.contrib.auth.views.password_reset_confirm', {'template_name': 'password_reset_confirm.html'}),
	(r'^password_reset/complete/$', 'django.contrib.auth.views.password_reset_complete', {'template_name': 'password_change_done.html'}),
	
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings


from mainsite.models import News
from mainsite.feeds import NewsFeed

feeds = {
	'noticias': NewsFeed,
}

info_dict = {
	'queryset': News.objects.filter(is_published=True),
	'date_field': 'date',
	'allow_empty': 1,
}


admin.autodiscover()

urlpatterns = patterns('',
	(r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
	(r'^dynamic-media/jsi18n/$', 'django.views.i18n.javascript_catalog'), 

	#(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	(r'^admin/(.*)', admin.site.root),

	(r'^gestor/api/', include('gestor.api.urls')),
	(r'^gestor/', include('gestor.urls')),
	(r'^accounts/', include('accounts.urls')),
	(r'^formacao/', include('formacao.urls')),
	
	(r'^users/(?P<username>([A-z]|[0-9]|[_])+)/$', 'accounts.views.profile'),
	(r'^users/(?P<username>([A-z]|[0-9]|[_])+)/curriculum/$', 'cvmanager.views.curriculum'),

	(r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
	
	# News Archives
	(r'^noticias/arquivo/$', 'mainsite.views.archive'),
	(r'^noticias/arquivo/(?P<year>\d{4})/$', 'django.views.generic.date_based.archive_year', dict( info_dict, template_name='news_archive_year.html' )),
	(r'^noticias/arquivo/(?P<year>\d{4})/(?P<month>\w{1,2})/$', 'django.views.generic.date_based.archive_month', dict( info_dict, 
																													   month_format='%m',
																													   template_name='news_archive_month.html',
																													   extra_context={'truncate':'true'})),
	(r'^noticias/arquivo/(?P<year>\d{4})/(?P<month>\w{1,2})/(?P<day>\w{1,2})/$', 'django.views.generic.date_based.archive_day', dict( info_dict,
																																	  month_format='%m',
																																	  template_name='news_archive_day.html',
																																	  extra_context={'truncate':'true'})),
	
	(r'^noticias/(?P<object_id>\d+)/$', 'mainsite.views.news_detail', {'template_name': 'news_detail.html'}),
	
	(r'^noticias/create/$', 'mainsite.views.create_news'),

	(r'^noticias/pesquisar/$', 'mainsite.views.search_news'),
	
	# New site (hard-coded, no more flat pages)
	(r'^$', 'mainsite.views.news_index', dict( info_dict, template_name='index.html' )),
	(r'^carreiras/$', 'django.views.generic.simple.direct_to_template', {'template': 'carreiras.html'}),
	(r'^contactos/$', 'django.views.generic.simple.direct_to_template', {'template': 'contactos.html'}),
	(r'^parceiros/$', 'django.views.generic.simple.direct_to_template', {'template': 'parceiros.html'}),
	(r'^servicos/$', 'django.views.generic.simple.direct_to_template', {'template': 'servicos.html'}),
	(r'^sobre/$', 'django.views.generic.simple.direct_to_template', {'template': 'sobre.html'}),
	
	# RH's Survey
	(r'^rh/$', 'django.views.generic.simple.direct_to_template', {'template': 'inquerito.html'}),
	
	# Public curriculums - must be the last one.
	(r'^(?P<username>([A-z]|[0-9]|[_])+)/$', 'cvmanager.views.public_curriculum'),
)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from sorl.thumbnail.fields import ImageWithThumbnailsField

from django.conf import settings

class UserProfile(models.Model):
	
	user = models.ForeignKey(User, unique=True)
	
	im = models.CharField("IM", max_length=40, blank=True, null=True)
	
	organization = models.CharField("Organization", max_length=20, default='jeKnowledge', null=True)
	title = models.CharField("Position", max_length=40, blank=True, null=True)
	description = models.TextField(blank=True, null=True)
	
	photo = ImageWithThumbnailsField(
		upload_to="photos",
		default=settings.DEFAULT_AVATAR,
		thumbnail={'size':(80,80)},
		extra_thumbnails={
			'small': {'size':(40,40)},
		},
	)
	
	class Meta:
		permissions = (('view_profiles', 'View all Profiles'),
					   ('can_search_everything', 'Search Everything'),)
		
	def __unicode__(self):
		return u"%s's Profile" % self.user.get_full_name()
		
	def get_absolute_url(self):
		return "/users/%s/" % self.user.username
		
	def photo_is_default(self):
		return self.photo == settings.DEFAULT_AVATAR
	
	def delete_photo(self):
		self.photo.delete()
		self.photo = settings.DEFAULT_AVATAR
		self.save()

cvmanager/models.py
from django.db import models
from django.contrib.auth.models import User

from cvmanager.utils import COURSES_CHOICES
import datetime

class CurriculumVitae(models.Model):
	owner = models.ForeignKey(User, unique=True)
	address = models.TextField()
	phone = models.CharField("PhoneNumber",max_length=100)
	homepage = models.CharField("Webpage",max_length=40,blank=True,null=True)
	
	course = models.CharField(max_length=128,choices=[ (c,c) for c in COURSES_CHOICES ])
	course_year = models.IntegerField(choices=[ (n,str(n)) for n in range(1,7) ] )
	
	complements = models.TextField(blank=True,null=True)
	proficient_areas = models.TextField(blank=True,null=True)
	foreign_langs = models.TextField("Foreign Languages",blank=True,null=True)
	computer_skills = models.TextField("Computer Skills",blank=True,null=True)
	other_skills = models.TextField("Other Skills",blank=True,null=True)
	interests = models.TextField(blank=True,null=True)
	
	set_date = models.DateField(auto_now_add=True)
	
	def save(self):
		self.set_date = datetime.datetime.today()
		super(CurriculumVitae, self).save()
	
	def __unicode__(self):
		return u"%s's Curriculum" % self.owner.get_full_name()
	
	def get_absolute_url(self):
		return "/users/%s/curriculum" % self.owner.username
		
	def get_public_url(self):
		return "/%s/" % self.owner.username
	
	def check_user(self, user):
		if not user.has_perm('cvmanager.can_view_cv') or not user is self.owner:
			return False
		else: return True
			
	def check_owner(self, user):
		if not user is self.owner: return False
		else: return True

	class Meta:
		permissions = ( ('can_view_cv','Can view CVs'), 
						('can_view_team_cv', "Can view team's CVs"),
						('can_view_cv_details','View CV details'),)

gestor/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

from activitystream.models import Activity

class ProjectManager(models.Manager):
	def get_query_set(self):
		return super(ProjectManager,self).get_query_set().filter(active=True)


class Project(models.Model):
	name = models.CharField(max_length=100, default=None)
	description = models.TextField(blank=True)
	active = models.BooleanField(default=True)
	manager = models.ForeignKey(User, related_name='projects_managed')
	team = models.ManyToManyField(User, related_name = 'projects_working')
	start_date = models.DateField()
	end_date = models.DateField()
	
	objects = models.Manager()
	workspace = ProjectManager()
	
	class Meta:
		ordering = ["-start_date"]
		permissions = [ ('view_project','Can view Projects'), 
						('view_intern_projects', 'Can view intern Projects'),
						('view_late_projects', 'Can view late Projects'),
						('view_late_users', 'Can view late Users') ]
	
	def __unicode__(self):
		return u"%s" % self.name
		
	def get_absolute_url(self):
		return "/gestor/project/%d/" % self.id
		
	def has_user(self,user):
		if user in self.team.all() or user == self.manager:
			return True
		return False
		
	def check_user(self,user):
		if not ( user.has_perm('gestor.view_project') or self.has_user(user) or (user.has_perm('gestor.view_intern_projects') and self.isIntern()) ):
			return False
		else: return True
	
	def check_manager(self, user, perm):
		if user != self.manager and not user.has_perm('gestor.' + perm + '_project'):
			return False
		else: return True
	
	def isIntern(self):
		return self.name.split('-')[0].lower() == 'jk'
	
	def ratio(self):
		done = self.actionitem_set.filter(done=True).count()
		total = self.actionitem_set.all().count()
		if total:
			return float(done) / total
		else:
			return 0
			
	def percentage(self):
		return str(int(round(self.ratio() * 100))) + "%"
	
	def createActivity(self, action):
		activity = Activity( message_type = Activity.MSG_GESTOR_PROJECT, 
							 action_type = action, 
							 object_id = self.id,
							 message = self.name )
		activity.save()
	
	def save(self):
		new_object = not self.id
		
		super(Project, self).save() # Call the "real" save() method
		
		if new_object:
			action = Activity.ACTION_CREATE
		else:
			action = self.active and Activity.ACTION_EDIT or Activity.ACTION_CLOSE
		self.createActivity(action)
						     
	    
	def delete(self):
		super(Project, self).delete() # Call the "real" delete() method
		self.createActivity(Activity.ACTION_DELETE)

class ActionItem(models.Model):
	project = models.ForeignKey(Project)
	title = models.CharField(max_length=100, default=None)
	description = models.TextField(blank=True, null=True)
	author = models.ForeignKey(User, related_name='actionitem_set')
	targets = models.ManyToManyField(User, related_name = 'actionitem_todo')
	set_date = models.DateField(auto_now=True)
	due_date = models.DateField(blank=True, null=True)
	done = models.BooleanField(default=False)
	priority = models.IntegerField(default=2, choices=((1, 'High') ,(2, 'Medium'), (3, 'Low')) )

	class Meta:
		ordering = ('done', 'priority', 'due_date')
	
	def __unicode__(self):
		return u"%s" % self.title
	
	def get_absolute_url(self):
		return "/gestor/action/%s/" % self.id 
	
	def createActivity(self, action):
		activity = Activity( message_type = Activity.MSG_GESTOR_ACTION_ITEM, 
							 action_type = action, 
							 object_id = self.id,
							 message = self.title )
		activity.save()
	
	def save(self):
		new_object = not self.id
		
		super(ActionItem, self).save() # Call the "real" save() method
		
		if new_object:
			action = Activity.ACTION_CREATE
		else:
			action = not self.done and Activity.ACTION_EDIT or Activity.ACTION_CLOSE
		self.createActivity(action)
						     
	    
	def delete(self):
		super(ActionItem, self).delete() # Call the "real" delete() method
		self.createActivity(Activity.ACTION_DELETE)	
	

class Note(models.Model):
	project = models.ForeignKey(Project)
	title = models.CharField(max_length=100, default=None)
	description = models.TextField(blank=True, null=True)
	author = models.ForeignKey(User)
	set_date = models.DateField(auto_now=True)
	
	class Meta:
		ordering = ["-set_date"]

	def __unicode__(self):
		return u"%s" % self.title
	
	def get_absolute_url(self):
		return "/gestor/note/%s/" % self.id
	
	def createActivity(self, action):
		activity = Activity( message_type = Activity.MSG_GESTOR_NOTE, 
							 action_type = action, 
							 object_id = self.id,
							 message = self.project.name )
		activity.save()
		
	def save(self):
		new_object = not self.id
		
		super(Note, self).save() # Call the "real" save() method
		
		if new_object:
			action = Activity.ACTION_CREATE
		else:
			action = Activity.ACTION_EDIT
		self.createActivity(action)
						     
	def delete(self):
		super(Note, self).delete() # Call the "real" delete() method
		self.createActivity(Activity.ACTION_DELETE)		
			
class ActionNote(models.Model):
	actionitem = models.ForeignKey(ActionItem)
	description = models.TextField(blank=True, null=True)
	author = models.ForeignKey(User)
	set_date = models.DateField(auto_now=True)
	
	class Meta:
		ordering = ["-set_date"]

	def __unicode__(self):
		return u"%s" % self.actionitem

	def get_absolute_url(self):
		return "/gestor/actionnote/%s/" % self.id

	def createActivity(self, action):
		activity = Activity( message_type = Activity.MSG_GESTOR_ACTION_NOTE, 
							 action_type = action, 
							 object_id = self.id,
							 message = self.actionitem.title )
		activity.save()
		
	def save(self):
		new_object = not self.id
		
		super(ActionNote, self).save() # Call the "real" save() method
		
		if new_object:
			action = Activity.ACTION_CREATE
		else:
			action = Activity.ACTION_EDIT
		self.createActivity(action)
						     
	def delete(self):
		super(ActionNote, self).delete() # Call the "real" delete() method
		self.createActivity(Activity.ACTION_DELETE)		
		

accounts/forms.py
from django.forms import *
from accounts.models import UserProfile
from django.contrib.auth.models import User

from django.contrib.auth.forms import UserChangeForm
from django.utils.translation import ugettext_lazy as _

from accounts.widgets import ImageWidget
from accounts.fields import LimitedImageField

from django.conf import settings

class UserProfileForm(ModelForm):
	user = ModelChoiceField(queryset=User.objects.all(),widget=HiddenInput())
	photo = LimitedImageField(widget=ImageWidget(UserProfile), required=False)
	
	class Meta:
		model = UserProfile
	
	def clean(self):
		res = super(UserProfileForm, self).clean()
		print self._errors
		if 'photo' in self._errors:
			self.fields['photo'].widget.instance = self.instance
		
		return res
	
	def save(self, *args, **kwargs):
		if 'photo' in self.changed_data and self.instance and self.instance.photo:
			if not self.instance.photo_is_default():
				self.instance.photo.delete()
		
		resp = super(UserProfileForm, self).save(*args, **kwargs)
		
		if self.data.has_key('remove_pic') and not self.instance.photo_is_default():
			resp.delete_photo()
		
		return resp

class UserProfileAdminForm(UserProfileForm):
	user = ModelChoiceField(queryset=User.objects.all())

class UserForm(UserChangeForm):
	username = CharField(_('username'), help_text=_("30 characters or fewer (letters, digits and underscores). Changing this will change your public curriculum's URL."))
	
	class Meta:
		model = User
		fields = ('username','first_name','last_name','email')
		

accounts/views.py
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect

from accounts.models import UserProfile
from accounts.forms import UserProfileForm, UserForm

from django.contrib.auth.decorators import login_required

from gestor.utils import dist, work_together, mergeLists
from common.utils import render
from common.views import PermissionDenied

# Redirects

@login_required
def redirect_to_profile(request):
	return HttpResponseRedirect('/users/' + request.user.username)
	
# Accounts Views
	
@login_required
def profile(request,username):
	u = get_object_or_404(User, username = username)
	
	if not (request.user == u or request.user.has_perm('accounts.view_profiles') or work_together(u, request.user)):
		return PermissionDenied(request)
	
	current_projects = mergeLists(u.projects_working.filter(active=True), u.projects_managed.filter(active=True))
	past_projects = mergeLists(u.projects_working.filter(active=False), u.projects_managed.filter(active=False))
	todo_list = [ [item, dist(item.due_date)] for item in u.actionitem_todo.filter(done=False) ]
	
	try: profile = u.get_profile()
	except UserProfile.DoesNotExist: profile = None
	
	return render(request,'user_profile.html',{'u':u,'current_projects':current_projects,'past_projects':past_projects,'todo_list':todo_list, 'profile':profile})

@login_required
def edit_my_profile(request):
	u = request.user
	
	try: profile = u.get_profile()
	except UserProfile.DoesNotExist: profile = None
	
	if request.method == 'POST':
		POST = request.POST.copy()
		POST['user'] = u.id
		
		profile_form = UserProfileForm(POST, request.FILES, instance=profile)
		user_form = UserForm(request.POST, request.FILES, instance=u)
		
		if user_form.is_valid() and profile_form.is_valid():
			u = user_form.save()
			profile = profile_form.save()
			profile.user = u
			
			request.user.message_set.create(message="Your Profile was updated")
			
			return HttpResponseRedirect(profile.get_absolute_url())
	else:
		user_form = UserForm(instance=u)
		
		if profile: profile_form = UserProfileForm(instance=profile)
		else: profile_form = UserProfileForm(initial={'user':request.user})
		
	return render(request, 'edit_profile.html', {'profile_form':profile_form, 'user_form':user_form})

accounts/templates/edit_profile.html
{% extends "base.html" %}

{% block title %}Edit Profile{% endblock title %}


{% block content %}
	<h1>Edit your Profile</h1>
	
	<fieldset>
		<form enctype="multipart/form-data" action="" method="POST">
			<table style='border: 0px;'>
				{{ user_form.as_table }}
				{{ profile_form.as_table }}
			</table>
			
			<br /><input type="submit" value="Save" />
		</form>
	</fieldset>
{% endblock %}

accounts/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock title %}


{% block content %}

	<h1>Login</h1>
	
	<div class="note_form">
		<fieldset>
			<form method="post" action=".">
				{{ form.as_ul }}
				<br /><a href="/accounts/password_reset"><small>Forgot your password?</small></a>
				<div class="clear"><input type="submit" value="login" /></div>
				<input type="hidden" name="next" value="{{ next }}" />
			</form>
		</fieldset>
	</div>

{% endblock %}

accounts/templates/password_change.html
{% extends "base.html" %}

{% block title %}Change Password{% endblock title %}


{% block content %}

	<h1>Change Password</h1>

	<fieldset>
		<form method="post" action="">
			{{ form.as_ul }}
			<div class="clear"><input type="submit" value="Change" /></div>
		</form>
	</fieldset>


{% endblock %}

accounts/templates/password_change_done.html
{% extends "base.html" %}

{% block title %}Password Changed{% endblock title %}


{% block content %}

	<h1>Changed Password</h1>
	
	<p>Your password was changed with success.</p>


{% endblock %}

accounts/templates/password_reset.html
{% extends "base.html" %}

{% block content %}

	<h1>Password Reset</h1>
	
	<p>Forgot your password? Enter your email below and we'll send you details on how to reset it.</p>
	
	<fieldset>
		<form method="post" action="">
			{{ form.as_ul }}
			<div class="clear"><input type="submit" value="Send" /></div>
		</form>
	</fieldset>


{% endblock %}

accounts/templates/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}

	<h1>Password Reset</h1>

	<fieldset>
		<form method="post" action="">
			{{ form.as_ul }}
			<div class="clear"><input type="submit" value="Reset" /></div>
			<input type="hidden" name="next" value="{{ next }}" />
		</form>
	</fieldset>


{% endblock %}

accounts/templates/password_reset_done.html
{% extends "base.html" %}

{% block content %}

	<h1>Password Reset</h1>
	
	<p>Success! Check your email and follow the instructions.</p>


{% endblock %}

accounts/templates/user_profile.html
{% extends "base.html" %}
{% load humanize %}
{% load datecolor %}
{% load markup %}

{% load cv_utils %}
{% load proj_utils %}

{% block title %}{{u.get_full_name}}{% endblock title %}

{% block content %}
	<div class="u_profile vcard">
		
		<h1 class="fn">{{u.get_full_name}}</h1>

		<div class="status">
			{% if u.is_staff %}
				<b>Admin</b>
			{% endif %}
		</div>
		
		<h3>Personal info {% if request.user|equals:u %}<a href="/accounts/edit_profile"><img src="{{MEDIA_URL}}icons/pencil.png" height="12px" alt="Edit your Profile" title="Edit your Profile" /></a>{% endif %}</h3>
		<div class="personal-info">
			{% if profile.photo %}
				{% if not profile.photo_is_default %}
					<a href="{{profile.photo.url}}" target='_blank'><img class="photo" src="{{profile.photo.thumbnail}}" alt={{u.get_full_name}} /></a>
				{% else %}
					<img class="photo" src="{{profile.photo.thumbnail}}" alt={{u.get_full_name}} />
				{% endif %}
			{% endif %}
			
			<p><b class="label">E-mail:</b> <a href="mailto:{{u.email}}" class="email">{{u.email}}</a></p>
			
			{% if perms.cvmanager.can_view_cv_details or request.user|equals:u %}
			{% if profile.im %}<p><b class="label">IM:</b> {{profile.im}}</p>{% endif %}
			
			<p><b class="label">Last Visit:</b> {{u.last_login|naturalday}}</p>
			<p><b class="label">User Since:</b> {{u.date_joined|naturalday}}</p>
			{% endif %}
						
			{% if profile %}<span class="org" style="display: none">{{ profile.organization }}</span>{% else %}
			<span class="org" style="display: none">jeKnowledge</span>{% endif %}
		</div>
		
		<div class="clear" />
		
		{% if profile or request.user|equals:u %}
		<h3>Career info</h3>
		{% if not profile %}
			<p>You don't have Career info yet! <a href="/accounts/edit_profile">Edit your profile here.</a></p>
		{% else %}
			<div class="career-info">
				<p><b class="label">Organization:</b> {{profile.organization}}</p>
				{% if profile.title %}<p><b class="label">Position:</b> {{profile.title}}</p>{% endif %}
				{% if profile.description %}{{profile.description|force_escape|textile}}{% endif %}
			</div>
		{% endif %}
		{% endif %}
		
		<h3>Curriculum Vitae {% if request.user|equals:u %}<a href="/accounts/edit_curriculum"><img src="{{MEDIA_URL}}icons/pencil.png" height="12px" alt="Edit your Curriculum" title="Edit your Curriculum" /></a>{% endif %}</h3>
		
		{% if perms.cvmanager.can_view_cv or request.user|can_view_this_cv:u %}
			{% ifequal u.curriculumvitae_set.count 0 %}
				This user doesn't have a CV yet.
			{% else %}
				{% if perms.cvmanager.can_view_cv_details or request.user|equals:u %}
				<a href="{{u.get_absolute_url}}curriculum/">View {{u.get_full_name}}'s full CV</a>
   				{% else %}
				<a href="/{{ u.username }}/">View {{u.get_full_name}}'s public CV</a>
				{% endif %}
				
				{% ifequal request.user u %}
					<br /><a href="/{{ u.username }}/">Use this URL to share your public CV</a>
				{% endifequal %}
			{% endifequal %}
		{% else %}
			You do not have permissions to view this CV.
		{% endif %}
		
		{% if perms.cvmanager.can_view_cv_details or request.user|manages_user:u %}
		
			{% if current_projects %}
				<h3>Current Projects</h3>
				<ul class="projects">
					{% for project in current_projects %}
						<li><a href="{{project.get_absolute_url}}">{{project.name}}</a>
						{% ifequal project.manager u  %}
							(Manager)
						{% endifequal %}
						</li> 
					{% endfor %}
				</ul>
			{% endif %}
   
   
			{% if past_projects %}
				<h3>Past Projects</h3>
				<ul class="projects">
					{% for project in past_projects %}
						<li><a href="{{project.get_absolute_url}}">{{project.name}}</a>
						{% ifequal project.manager u  %}
							(Manager)
						{% endifequal %}
						</li> 
					{% endfor %}
				</ul>
			{% endif %}
		
			{% if todo_list %}
				<h3>Todo List</h3>
				<ul>
					{% for item, dist in todo_list %}
						<li class="{{item|colorstatus}}">
							<a href="{{item.get_absolute_url}}" title="Dues: {%if dist%}{{dist}} days{%else%}Never{%endif%}. Priority: {{item.get_priority_display}}">{{ item.title }}</a>
						</li> 
					{% endfor %}
				</ul>
			{% endif %}
			
		{% endif %}
		
		
	</div>
{% endblock %}